# Generated by Django 5.1.4 on 2024-12-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название Модели')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Категория')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка категории')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Поле slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='digitalstore1.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('color_code', models.CharField(max_length=10, verbose_name='Код цвета')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка')),
                ('width', models.CharField(max_length=10, verbose_name='Ширина')),
                ('depth', models.CharField(max_length=10, verbose_name='Глубина')),
                ('height', models.CharField(max_length=10, verbose_name='Высота')),
                ('frame', models.CharField(max_length=100, verbose_name='Корпус')),
                ('release_date', models.CharField(max_length=100, verbose_name='Дата выхода')),
                ('battery', models.CharField(blank=True, max_length=100, null=True, verbose_name='Аккумулятор товара')),
                ('technologies', models.CharField(max_length=100, verbose_name='Технологии')),
                ('diagonal', models.FloatField(verbose_name='Диагональ')),
                ('back_cam', models.CharField(blank=True, max_length=100, null=True, verbose_name='Задняя камера')),
                ('front_cam', models.CharField(blank=True, max_length=100, null=True, verbose_name='Передняя камера')),
                ('os', models.CharField(max_length=100, verbose_name='Операционная система')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Slug товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('memory', models.IntegerField(blank=True, default=0, null=True, verbose_name='Память')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='digitalstore1.category', verbose_name='Категория товара')),
                ('modal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalstore1.modalproduct', verbose_name='Модель товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Картинка товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='digitalstore1.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
            },
        ),
    ]
