# Generated by Django 5.1.4 on 2024-12-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore1', '0002_region_customer_favoriteproduct_order_orderproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
